When using RxGORM each entity that you persist to the database is known as a domain class.

If you are using RxGORM within Grails you can create a domain class with the `create-domain-class` command provided by the command line. Alternatively if you are not using Grails simply creating a Groovy class with `src/main/groovy` of your project will suffice.

A domain class must as a minimum implement the link:api/grails/gorm/rx/RxEntity.html[RxEntity] trait.

However, when using RxGORM for MongoDB you should instead implement the `grails.gorm.rx.mongodb.RxMongoEntity` trait. For example:

[source,groovy]
----
package example

import grails.gorm.rx.mongodb.*
import org.bson.types.ObjectId

class Book implements RxMongoEntity<Book> {
    ObjectId id
    String title
}
----

NOTE: The type is provided as a generic argument to the `RxMongoEntity` trait. This is important to ensure the correct return signatures are produced for methods provided by the trait.

In addition, for MongoDB an `id` of type `ObjectId` is required.

For more information on domain modelling in GORM, take a look at the http://docs.grails.org/latest/guide/GORM.html#domainClasses[GORM user guide documentation] on the subject.
