If you wish to use GORM for Hibernate outside of a Grails application you should declare the necessary dependencies, for example in Gradle:

[source,groovy]
----
compile "org.grails:grails-datastore-gorm-hibernate4:VERSION"
----

Then annotate your entities with the `grails.gorm.annotation.Entity` annotation:

[source,groovy]
----
@Entity
class Person {
    String name
}
----

Then you need to place the bootstrap logic somewhere in your application which uses `HibernateDatastoreSpringInitializer`:

[source,groovy]
----
def initializer = new HibernateDatastoreSpringInitializer(Person)
def applicationContext = initializer.configure()

println Person.count()
----

For configuration you can either pass a map or an instance of the `org.springframework.core.env.PropertyResolver` interface:

[source,groovy]
----
def initializer = new HibernateDatastoreSpringInitializer(['hibernate.log_sql':'true'], Person)
def applicationContext = initializer.configure()

println Person.count()
----

If you are using Spring with an existing `ApplicationContext` you can instead call `configureForBeanDefinitionRegistry` prior to refreshing the context. You can pass the Spring `Environment` object to the constructor for configuration:

[source,groovy]
----
ApplicationContext myApplicationContext = ...
def initializer = new HibernateDatastoreSpringInitializer(myApplicationContext.getEnvironment(), Person)
initializer.configureForBeanDefinitionRegistry(myApplicationContext)

println Person.count()
----

Note in this case GORM expects there to be a bean named `dataSource` present.